version: '3.1'
services:
  book-video-link-wiremock:
    image: rodolpheche/wiremock
    container_name: book-video-link-wiremock
    restart: always
    ports:
      - "9091:8080"

  book-video-link-test-redis:
    image: redis
    container_name: book-video-link-test-redis
    ports:
      - 6379:6379
