---
# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: hmpps-book-video-link
  alertSeverity: digital-prison-service-dev

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"