---
# Values here are the same across all environments
generic-service:
  nameOverride: hmpps-book-video-link
  productId: DPS004
  serviceAccountName: book-a-video-link

  image:
    repository: quay.io/hmpps/hmpps-book-video-link
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  replicaCount: 4

  ingress:
    enabled: true
    tlsSecretName: hmpps-book-video-link-cert
    path: /

  jobs:
    cronspec: "0 8,12,15 * * *"
  # jobs will run at 9am, 1pm and 4pm

  env:
    REMOTE_AUTH_STRATEGY: "true"
    WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
    VIDEO_LINK_ENABLED_FOR: "WWI,TSI,HEI,BWI,NMI,EYI,BNI,PBI,BMI,NWI,PNI,BZI,PVI,EXI,WSI"
    TOKENVERIFICATION_API_ENABLED: true
    FEATURE_FLAG_OUTAGE_BANNER_ENABLED: false
    REDIS_ENABLED: true
    REDIS_TLS_ENABLED: true
    NODE_ENV: production


  namespace_secrets:
    hmpps-book-video-link:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      API_SYSTEM_ID: "API_SYSTEM_ID"
      API_SYSTEM_SECRET: "API_SYSTEM_SECRET"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"
      GOOGLE_SERVICE_ACCOUNT_KEY: "GOOGLE_SERVICE_ACCOUNT_KEY"
      GOOGLE_TAG_MANAGER_KEY: "GOOGLE_TAG_MANAGER_KEY"
      NOTIFY_API_KEY: "NOTIFY_API_KEY"
      SESSION_COOKIE_SECRET: "SESSION_COOKIE_SECRET"
    hmpps-book-video-link-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  livenessProbe:
    httpGet:
      path: /ping
  readinessProbe:
      httpGet:
        path: /ping

  allowlist:
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  targetApplication: hmpps-book-video-link
  alertSeverity: digital-prison-service-dev