---
# Values here are the same across all environments
generic-service:
  nameOverride: hmpps-book-video-link

  image:
    repository: quay.io/hmpps/hmpps-book-video-link
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  replicaCount: 4

  ingress:
    enabled: true
    enable_whitelist: true
    cert_secret: hmpps-book-video-link-cert
    path: /
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: "100"

  jobs:
    cronspec: "0 8,12,15 * * *"
  # jobs will run at 9am, 1pm and 4pm

  env:
    REMOTE_AUTH_STRATEGY: "true"
    WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
    VIDEO_LINK_ENABLED_FOR: "WWI,TSI,HEI,BWI,NMI,EYI,BNI,PBI,BMI,NWI,PNI,BZI,PVI,EXI,WSI"
    TOKENVERIFICATION_API_ENABLED: true
    FEATURE_FLAG_OUTAGE_BANNER_ENABLED: false
    REDIS_ENABLED: true

  allowlist:
    groups:
      - moj_cloud_platform
      - digital_staff_and_mojo

generic-prometheus-alerts:
  targetApplication: hmpps-book-video-link
  alertSeverity: digital-prison-service-dev