---
# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: hmpps-book-video-link

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"

allowlist:
  petty-france-wifi: "213.121.161.112/28"
  global-protect: "35.176.93.186/32"