apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "app.name" . }}-update-events
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.jobs.cronspec | quote }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          serviceAccountName: book-a-video-link
          restartPolicy: Never
          activeDeadlineSeconds: 240
          containers:
            - name: {{ template "app.name" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - node
                - backend/jobs/eventsJob
{{ include "deployment.envs" . | nindent 14 }}

