apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-book-video-link-update-events
spec:
  schedule: {{ .Values.jobs.cronspec | quote }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          serviceAccountName: book-a-video-link
          restartPolicy: Never
          activeDeadlineSeconds: 240
          containers:
            - name: hmpps-book-video-link
              image: {{ with index .Values "generic-service" }}{{ .image.repository }}:{{ .image.tag }}{{ end }}
              args:
                - node
                - backend/jobs/eventsJob
{{ include "deployment.envs" . | nindent 14 }}

