apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-events-job
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "59 * * * *"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      suspend: {{ .Values.jobs.suspend }}
      template:
        spec:
          containers:
            - name: {{ template "app.name" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - node
                - backend/jobs/eventsJob
{{ include "deployment.envs" . | nindent 14 }}
          restartPolicy: Never
          activeDeadlineSeconds: 240
