  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

generic-service:

  ingress:
    host: book-video-link.prison.service.justice.gov.uk
    
  env:
    BOOK_VIDEO_LINK_UI_URL: https://book-video-link.prison.service.justice.gov.uk/
    API_ENDPOINT_URL: https://prison-api.prison.service.justice.gov.uk/
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth/
    API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api.service.justice.gov.uk/
    API_PRISONER_OFFENDER_SEARCH_ENDPOINT_URL: https://prisoner-search.prison.service.justice.gov.uk/
    API_PRISON_REGISTER_ENDPOINT_URL: https://prison-register.hmpps.service.justice.gov.uk/
    API_HMPPS_USER_PREFERENCE_ENDPOINT_URL: https://hmpps-user-preferences.hmpps.service.justice.gov.uk/
    HMPPS_COOKIE_NAME: hmpps-session-prod
    HMPPS_COOKIE_DOMAIN: book-video-link.prison.service.justice.gov.uk
    TOKENVERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
    VLBEVENT_EXPORT_SPREADSHEET_ID: "1bsFD9_ny9ihPhDRYVY7Xq4IxRbfiwBfWzabbYAciZ5Y"
    MANAGE_USERS_API_URL: https://manage-users-api.hmpps.service.justice.gov.uk/

  allowlist:
    royal-courts-of-justice: 178.248.34.43/32

    groups:
      - prisons
      - probation
      - moj_cloud_platform
      - digital_staff_and_mojo
      - analytic-platform

  # determine which slack channel alerts are sent to, via the correct Alert Manager receiver
  generic-prometheus-alerts:
    targetApplication: hmpps-book-video-link
    alertSeverity: elp_alerts