  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

generic-service:

  ingress:
    host: book-video-link.prison.service.justice.gov.uk
    
  env:
    BOOK_VIDEO_LINK_UI_URL: https://book-video-link.prison.service.justice.gov.uk/
    API_ENDPOINT_URL: https://prison-api.prison.service.justice.gov.uk/
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth/
    API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api.service.justice.gov.uk/
    API_PRISONER_OFFENDER_SEARCH_ENDPOINT_URL: https://prisoner-search.prison.service.justice.gov.uk/
    API_PRISON_REGISTER_ENDPOINT_URL: https://prison-register.hmpps.service.justice.gov.uk/
    API_HMPPS_USER_PREFERENCE_ENDPOINT_URL: https://hmpps-user-preferences.hmpps.service.justice.gov.uk/
    HMPPS_COOKIE_NAME: hmpps-session-prod
    TOKENVERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
    VLBEVENT_EXPORT_SPREADSHEET_ID: "1bsFD9_ny9ihPhDRYVY7Xq4IxRbfiwBfWzabbYAciZ5Y"
    MANAGE_USERS_API_URL: https://manage-users-api.hmpps.service.justice.gov.uk/


  allowlist:
    analyticplatform-1: 34.250.17.221/32
    analyticplatform-2: 34.251.212.33/32
    analyticplatform-3: 34.252.4.39/32
    ark-dom1-psn1: 51.247.4.0/24
    ark-dom1-psn2: 51.247.3.0/24
    dxc_webproxy1: 195.92.38.20/32
    dxc_webproxy2: 195.92.38.21/32
    dxc_webproxy3: 195.92.38.22/32
    dxc_webproxy4: 195.92.38.23/32
    quantum1: 62.25.109.197/32
    quantum2: 212.137.36.230/32
    quantum3: 195.92.38.16/28
    royal-courts-of-justice: 178.248.34.43/32

    groups:
      - prisons
      - probation

  # determine which slack channel alerts are sent to, via the correct Alert Manager receiver
  generic-prometheus-alerts:
    targetApplication: hmpps-book-video-link
    alertSeverity: elp_alerts