  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
generic-service:

  ingress:
    host: book-video-link-preprod.prison.service.justice.gov.uk

  env:
    BOOK_VIDEO_LINK_UI_URL: https://book-video-link-preprod.prison.service.justice.gov.uk/
    API_ENDPOINT_URL: https://prison-api-preprod.prison.service.justice.gov.uk/
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/
    API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-preprod.service.justice.gov.uk/
    API_PRISONER_OFFENDER_SEARCH_ENDPOINT_URL: https://prisoner-search-preprod.prison.service.justice.gov.uk/
    API_PRISON_REGISTER_ENDPOINT_URL: https://prison-register-preprod.hmpps.service.justice.gov.uk/
    API_HMPPS_USER_PREFERENCE_ENDPOINT_URL: https://hmpps-user-preferences-preprod.hmpps.service.justice.gov.uk/
    HMPPS_COOKIE_NAME: hmpps-session-preprod
    HMPPS_COOKIE_DOMAIN: hmpps-session-preprod
    TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    VLBEVENT_EXPORT_SPREADSHEET_ID: "1YUKHKsq9VftSLm6twO9F172gHDh6Xp8Tj6V1HEN6FbA"
    MANAGE_USERS_API_URL: https://manage-users-api-preprod.hmpps.service.justice.gov.uk/
