  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
generic-service:

  replicaCount: 2

  ingress:
    host: book-video-link-dev.prison.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        return 301 "https://book-a-video-link-dev.prison.service.justice.gov.uk";

  env:
    BOOK_VIDEO_LINK_UI_URL: https://book-video-link-dev.prison.service.justice.gov.uk/
    API_ENDPOINT_URL: https://prison-api-dev.prison.service.justice.gov.uk/
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/
    API_WHEREABOUTS_ENDPOINT_URL: https://whereabouts-api-dev.service.justice.gov.uk/
    API_PRISONER_OFFENDER_SEARCH_ENDPOINT_URL: https://prisoner-search-dev.prison.service.justice.gov.uk/
    API_PRISON_REGISTER_ENDPOINT_URL: https://prison-register-dev.hmpps.service.justice.gov.uk/
    API_HMPPS_USER_PREFERENCE_ENDPOINT_URL: https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk/
    HMPPS_COOKIE_NAME: hmpps-session-dev
    HMPPS_COOKIE_DOMAIN: book-video-link-dev.prison.service.justice.gov.uk
    TOKENVERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
    VLBEVENT_EXPORT_SPREADSHEET_ID: "18BcOjlGlVfK8Qr3V3fhqdfYj4XEUfQGRIcJwzJ3BB-Y"
    MANAGE_USERS_API_URL: https://manage-users-api-dev.hmpps.service.justice.gov.uk/